# Generated by Django 3.2 on 2022-02-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='marchantPaymentId',
            new_name='merchantPaymentId',
        ),
    ]
