# Generated by Django 3.2 on 2022-02-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_marchantpaymentid_paymenthistory_merchantpaymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='merchantPaymentId',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='決済ID'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan',
            field=models.CharField(editable=False, max_length=32, verbose_name='プランの種類'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='uid',
            field=models.CharField(editable=False, max_length=32, verbose_name='ユーザID'),
        ),
    ]
