# Generated by Django 3.2 on 2022-02-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20220219_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': '決済履歴', 'verbose_name_plural': '決済履歴'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='決済画面移動時刻'),
            preserve_default=False,
        ),
    ]
