# Generated by Django 3.2 on 2022-02-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_paymenthistory_payed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=32, verbose_name='プランの種類')),
            ],
            options={
                'verbose_name': 'プランの種類',
                'verbose_name_plural': 'プランの種類',
            },
        ),
    ]
