# Generated by Django 3.2 on 2022-02-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookstore.plan'),
        ),
    ]
