# Generated by Django 3.2.9 on 2021-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('access_count', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
