# Generated by Django 4.0 on 2021-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='blog.BlogUser'),
        ),
    ]
