# Generated by Django 4.0 on 2021-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloguser_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUserMoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser')),
            ],
        ),
    ]
