# Generated by Django 4.1.1 on 2022-09-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blogs',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blog.blog'),
        ),
    ]
