# Generated by Django 4.1.6 on 2023-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatappuser',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
