# Generated by Django 4.1.6 on 2023-02-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chatappuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatappuser',
            name='image',
        ),
    ]
