# Generated by Django 4.1.6 on 2023-02-04 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chatappuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sendername', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChatappMessages', to='chatapp.chatappuser')),
            ],
        ),
    ]
