# Generated by Django 4.0 on 2021-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToitterUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('following', models.ManyToManyField(blank=True, related_name='followed_by', to='toitter.ToitterUser')),
            ],
        ),
    ]
