name: "Django CI for Pull Request"

on:
  pull_request:
    paths:
      - '**'

jobs:
  test-container-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          python3 manage.py test blog.tests